### ISSUE TITLE
where can i find the corecrypto_static?

### ISSUE THREAD

**Issue by zenochen** [NyaMisty/AltServer-Linux#10]
Thanks for your job.

when compiling, my system didn't find the corecrypto library, I thought it is apple'code, so I used one of the github hosted, but says: cc/src/cc_clear.c:66:10: fatal error: 'corecrypto/fipspost_trace.h' file not found

and I found that some files is missing, can you give us your code, thanks.

**Comment by zenochen** [comment]
I found it in apple website
https://developer.apple.com/security/
search Download corecrypto source (2020 OS Releases)

**Comment by ufilme** [comment]
How did you install the corecrypto lib? It gives me an error on `make` saying it's missing a `test_vectors/h2c_sswu.kat` file. And it's actually missing in the folder...

**Comment by pwn64** [comment]
^

**Comment by hammyexe** [comment]
> How did you install the corecrypto lib? It gives me an error on `make` saying it's missing a `test_vectors/h2c_sswu.kat` file. And it's actually missing in the folder...

Im having the same issue

**Comment by MeLThRoX** [comment]
> > How did you install the corecrypto lib? It gives me an error on `make` saying it's missing a `test_vectors/h2c_sswu.kat` file. And it's actually missing in the folder...
> 
> Im having the same issue

Needed to run `scripts/convert_h2c_testvectors.py <srcroot>`. This fixes the problem.

But the next problem is that it can't identify the ciphers:
```
error: use of undeclared identifier 'rsa_signature_2048_sha384_test'
error: use of undeclared identifier 'rsa_signature_test'
error: use of undeclared identifier 'rsa_signature_2048_sha256_test'
error: use of undeclared identifier 'rsa_pss_2048_sha256_mgf1_32_test'
.
.
.
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```
Do I need to install OpenSSL or something?

**Comment by ufilme** [comment]
> 

Now I'm getting another file missing...
```make
In file included from /home/ubuntu/corecrypto/ccrng/crypto_test/crypto_test_ccrng_fortuna.c:24:
In file included from /home/ubuntu/corecrypto/corecrypto_test/include/ccshadow.h:26:
/home/ubuntu/corecrypto/corecrypto_test/include/ccshadow_decls.h:20:10: fatal error: 'mach/mach_time.h' file not found
#include <mach/mach_time.h>
         ^~~~~~~~~~~~~~~~~~
```

**Comment by clsx524** [comment]
mach_time is only available on mac or ios so the include would fail for linux.

My fix is to replace the include with a conditional if
```
#if CC_KERNEL || CC_DARWIN || CORECRYPTO_SIMULATE_POSIX_ENVIRONMENT
#include <mach/mach_time.h>
#endif
```

Besides, `scripts/convert_h2c_testvectors.py <srcroot>` is part of the process in make already, but it might not run because of missing python package in my system (my case) or python binary doesn’t exist (python3 might exist so you can create a symbolic link for python).

**Comment by D-06** [comment]
scripts/convert_h2c_testvectors.py <srcroot> seem doesn't work to me

srcroot/cch2c/test_vectors/h2c_sswu.kat
Traceback (most recent call last):
  File "scripts/convert_h2c_testvectors.py", line 151, in <module>
    convert(args.srcroot)
  File "scripts/convert_h2c_testvectors.py", line 139, in convert
    with open(output_file, "w") as fout:
FileNotFoundError: [Errno 2] No such file or directory: 'srcroot/cch2c/test_vectors/h2c_sswu.kat'

**Comment by NyaMisty** [comment]
Well if you guys have some basic linux knowledge, tests are not that important if you are sure that the library is good.
Simply patching out target corecrypto_perf and corecrypto_static would allow the make install procedure.

**Comment by 0x8FF** [comment]
@NyaMisty the cmake script is very broken

**Comment by NyaMisty** [comment]
> @NyaMisty the cmake script is very broken
> 
> 

Yep, but it configures fine.
Simply patch the Makefile or CMakeLists should be OK

**Comment by mrchilliballs** [comment]
when running `python3 scripts/convert_h2c_testvectors.py srcroot` I get  this error:
`srcroot/cch2c/test_vectors/h2c_sswu.kat
Traceback (most recent call last):
  File "/home/matheus/Downloads/corecrypto/scripts/convert_h2c_testvectors.py", line 151, in <module>
    convert(args.srcroot)
  File "/home/matheus/Downloads/corecrypto/scripts/convert_h2c_testvectors.py", line 139, in convert
    with open(output_file, "w") as fout:
FileNotFoundError: [Errno 2] No such file or directory: 'srcroot/cch2c/test_vectors/h2c_sswu.kat'
`
