### ISSUE TITLE
clould not find altserver

### ISSUE THREAD

**Issue by zenochen** [NyaMisty/AltServer-Linux#11]
I open the altstore, if use wifi, I click the sign in with Apple ID,  It shows the tip "clould not find altserver"

I tested with usb connected, it's ok.

**Comment by NyaMisty** [comment]
yep, cannot work over WiFi due to lack of avahi integration.
Currently no plan to support it :(

**Comment by NyaMisty** [comment]
Avahi support now seems viable, as usbfluxd does lots of dirty work for us.
To support WiFi sync, we can simply look at AltServer's mDNS broadcast and send it over avahi.

**Comment by NyaMisty** [comment]
Now supported
