### ISSUE TITLE
can't install altstore

### ISSUE THREAD

**Issue by firashacker** [NyaMisty/AltServer-Linux#15]
i'm using the usbmuxd version it just wouldn't establish notification connection if altstore is not opend on the device so can't install it just refresh i stiil have to use windows and connection over the wifi with usbmuxd2 whould not connect the altserver

anyway you did a great job and i liked this keep on you can replay to me if i'm wrong maybe i messed something 

i wish you can just create a simple tool to sign the ipa file on linux without altserver or installing it just sign with free apple id and the installation with ideviceinstaller

**Comment by NyaMisty** [comment]
The tools itself can achieve this, but I uploaded the wrong version. Fixed now
