### ISSUE TITLE
[Suggestion/Feature Request] Documentation

### ISSUE THREAD

**Issue by CITIZENSIXTYNINE** [NyaMisty/AltServer-Linux#2]
Maybe a simple readme would be useful to know how to use the program instead of having the user to tinker and find out how to have this work,

**Comment by JohnyBoy2128** [comment]
If you have figured out how to work this, I would be very excited to hear anything

**Comment by CITIZENSIXTYNINE** [comment]
no.

i wanted to figure it out, make a readme, submit a pr request and at least have something that can guide users.
