### ISSUE TITLE
AltServer never progresses past `Starting notification connection to device`

### ISSUE THREAD

**Issue by deatondg** [NyaMisty/AltServer-Linux#25]
I have compiled this for aarch64 on my Raspberry Pi 4, but running
```
./AltServer -u [UDID] -a [AppleID account] -p [AppleID password] [ipaPath.ipa]
```
never progresses past
```
Detected device:Davis’s iPad
Starting notification connection to device: Davis’s iPad
```
Replugging the device reprints the message.

I am unsure is this is related to running on aarch64 or not.

Minor modifications to the compilation process are required for aarch64. `-mno-default` is not supported, so this needs to be removed from the `CFLAGS`, static linking to `libcrypto` appears to be unsupported so `-static` needs to be removed from the `LDFLAGS`, and additionally `-mno-sse` is useless on aarch64 but `-fPIC` is required in the `CFLAGS` for AltSign. 

Any help is appreciated.

**Comment by Stardust-kyun** [comment]
I have the same issue. I downloaded the latest release, made it executable, and tried installing an ipa with the correct format:
```
./AltServer -u [UDID] -a [AppleID account] -p [AppleID password] [ipaPath.ipa]
```
It gives me the same output of:
```
Detected device:Maple
Starting notification connection to device: Maple
```
Not sure what to do.

**Comment by Stardust-kyun** [comment]
Found a working binary:
https://github.com/rileytestut/AltStore/files/7393624/AltServer.zip

**Comment by deatondg** [comment]
Do you have more info about how this file was created? I am running on aarch64, so this binary will not work for me.

**Comment by Stardust-kyun** [comment]
I found it here:
https://github.com/rileytestut/AltStore/issues/6#issuecomment-949145178

**Comment by deatondg** [comment]
Thanks! That was helpful.

The solution is in this issue https://github.com/NyaMisty/AltServer-Linux/issues/9.

**Comment by 0x8ff** [comment]
https://github.com/NyaMisty/AltServer-Linux/issues/14

**Comment by powenn** [comment]
Have same issues above 
Got stuck at sending notification 
Btw I wrote shell scripts to make easier to use 

https://github.com/powenn/AltServer-Linux-ShellScript

It will ask ur ID and password then auto fill in information with UDID 
When this project work,it might help to use

**Comment by powenn** [comment]
The older  release works on pinephone mobian !!!
But took 10 minutes to install Delta emulator

**Comment by NyaMisty** [comment]
Sorry guys, that's my fault.
In my second release I wrote the following code:
```
	bool installApp = ipaPath;
	if (optind == argc) {
		printf("Not supplying ipa, running in server mode!\n");
        installApp = false;
    } else if (optind + 1 == argc) {
		ipaPath = argv[optind];
	} else {
	
```
but the ipaPath is a pointer variable on stack. Only if ipaPath is NULL will the program continue.
I've fixed it, and as an apologization, I compiled armv7 & aarch64 version.

Thanks @jmans25 @powenn @zenochen

**Comment by powenn** [comment]
> Sorry guys, that's my fault.
> 
> In my second release I wrote the following code:
> 
> ```
> 
> 	bool installApp = ipaPath;
> 
> 	if (optind == argc) {
> 
> 		printf("Not supplying ipa, running in server mode!\n");
> 
>         installApp = false;
> 
>     } else if (optind + 1 == argc) {
> 
> 		ipaPath = argv[optind];
> 
> 	} else {
> 
> 	
> 
> ```
> 
> but the ipaPath is a pointer variable on stack. Only if ipaPath is NULL will the program continue.
> 
> I've fixed it, and as an apologization, I compiled armv7 & aarch64 version.
> 
> 
> 
> Thanks @jmans25 @powenn @zenochen

Thank for this update 👍
