### ISSUE TITLE
[Request] Install the Altstore app through AltServer-Linux and provide GUI

### ISSUE THREAD

**Issue by olivertzeng** [NyaMisty/AltServer-Linux#26]

**Comment by 0x8FF** [comment]
Idk if we will ever get a GUI from this project, but [here's the altstore app ipa](https://cdn.altstore.io/file/altstore/apps/altstore/1_4_8.ipa) if you'd like to have the app

**Comment by Practicalbutterfly5** [comment]
> Idk if we will ever get a GUI from this project, but [here's the altstore app ipa](https://cdn.altstore.io/file/altstore/apps/altstore/1_4_8.ipa) if you'd like to have the app

Hello, can you tell how you got this ipa. Or how to compile it?

**Comment by 0x8FF** [comment]
https://cdn.altstore.io/file/altstore/apps/altstore/1_4_8.ipa

**Comment by olivertzeng** [comment]
lol thanks a lot

**Comment by olivertzeng** [comment]
idk what command can i do to sideload ipa files?

**Comment by 0x8FF** [comment]
``./AltServer -u [UDID] -a [AppleID account] -p [AppleID password] [ipaPath.ipa]``

**Comment by powenn** [comment]
![image](https://user-images.githubusercontent.com/72635554/149650538-464a33d1-3242-44d1-aef5-6923eeea40e0.jpeg)

If you want,there is a TUI to use AltServer-Linux

**Comment by olivertzeng** [comment]
I want it! how can i install it?

**Comment by olivertzeng** [comment]
cool! i found it on your repo! full lot of thanks! from a taiwanese! Are you Taiwanese or Hongkongese btw?

**Comment by olivertzeng** [comment]
I found that you're Taiwanese, nice to meet you, you're in 板橋高中

**Comment by powenn** [comment]
> I found that you're Taiwanese, nice to meet you, you're in 板橋高中

That doesn't mean you have to make all people who views this issue know ,first it has no association to this issue and project,second u should pm rather than comment here

**Comment by olivertzeng** [comment]
ok
