### ISSUE TITLE
All Installed ipa crashes immediately 

### ISSUE THREAD

**Issue by Practicalbutterfly5** [NyaMisty/AltServer-Linux#28]
I compiled altserver using the instructions with alpine 3.15 docker container. It works perfectly as a daemon for refreshing apps , and ipa are installed. But all installed apps crash immediately when opened.

**Comment by powenn** [comment]
> I compiled altserver using the instructions with alpine 3.15 docker container. It works perfectly as a daemon for refreshing apps , and ipa are installed. But all installed apps crash immediately when opened.

On iOS 15 ?

**Comment by Practicalbutterfly5** [comment]
> On iOS 15 ?

Yes 15.1 ipados

**Comment by powenn** [comment]
> > On iOS 15 ?
> 
> 
> 
> Yes 15.1 ipados

Most of the reports of app crashes was caused by running iOS 15,seems it haven't add iOS 15 support yet

**Comment by Practicalbutterfly5** [comment]
There are 2 ways I have tried

1. Install altstore with windows (works). Then use either linux altserver or windows altserver daemon to install ipa via altstore. This works fine 
2. Install apps ipa directly using Altserver-Linux. App crashes.

**Comment by CannibalToast** [comment]
I'm having this same issue too. IOS 15.1 iPhone 7, 15.1 iPhone 8 Plus, and IOS 15.1 iPad Pro 10.5"

**Comment by lore-sys** [comment]
Im having the same issue too on iPhone 8, iOS **15.2**

**Comment by tinylabs** [comment]
Same here with iPad 9th edition IOS 15.3

**Comment by lonkelle** [comment]
Did you guys figure this out at all. It seems like some kind of unique installation edge case and I wanna help figure out how to fix it if you haven’t already?

**Comment by ivon852** [comment]
Current workaround is installing AltStore through  a Windows VM. And you can still resign apps on Linux.

**Comment by jkcoxson** [comment]
Riley Testut has fixed this issue on the upstream fork, this can easily be downstreamed. [PR](https://github.com/rileytestut/ldid/compare/2bd997097f3d88527f7ef6da1d46801a6bb96eac...4844a00d2512e72ecbcd5170339945726ea6fc3b#diff-ddf9f6bce91f3f624d346a7acd2a797ff72dd8bd17ab565d7488a0b33b42b840)
