### ISSUE TITLE
./PrefixHeader.pch:12:10: fatal error: 'cpprest/http_client.h' file not found

### ISSUE THREAD

**Issue by All3xJ** [NyaMisty/AltServer-Linux#32]
I followed all this:
![image](https://user-images.githubusercontent.com/20903913/153956799-781fb6c8-5073-4a2e-a185-ed71953b32c0.png)

But if I try to compile AltServer:
```
#       make NO_USBMUXD_STUB=1 NO_UPNP_STUB=1
make -C libraries/AltSign
make[1]: Entering directory '/root/AltServer-Linux/libraries/AltSign'
clang++ -Iminizip -I../libplist/include -I. -mno-sse -std=c++17  -o Account.cpp.o -c Account.cpp
In file included from Account.cpp:11:
./PrefixHeader.pch:12:10: fatal error: 'cpprest/http_client.h' file not found
#include <cpprest/http_client.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [Makefile:18: Account.cpp.o] Error 1
make[1]: Leaving directory '/root/AltServer-Linux/libraries/AltSign'
make: *** [Makefile:83: lib_AltSign] Error 2
```

**Comment by NyaMisty** [comment]
You need to learn some basic linux open source usage pattern lol

**Comment by NyaMisty** [comment]
(Note: that's because there's missing make install in my note)

**Comment by All3xJ** [comment]
> (Note: that's because there's missing make install in my note)
If you see, that is literally a screenshot of your installation guide in the README.md.... I did a make install of course... and didn't work. Anyway, now I can just use the docker image that you uploaded, instead of manually compile it
