### ISSUE TITLE
Issue installing Altstore

### ISSUE THREAD

**Issue by hammyexe** [NyaMisty/AltServer-Linux#33]
I get an error saying, "A device with this number 'example numbers' already exists on this team (35) But I do not have it installed.

**Comment by TropicLegend** [comment]
same issue here

**Comment by TimestaticYT** [comment]
Same for me!

**Comment by ancba** [comment]
Have you sloved this issuse?I met the same issuse

**Comment by TimestaticYT** [comment]
I needed to go to windows to install altstore but updates work fine with this

**Comment by powenn** [comment]
Same here,6s works fine,but 11 pro,XR,se2 have this issue,they both on iOS 14

**Comment by NyaMisty** [comment]
Please test out the latest v0.0.3-rc1 prerelease build:
https://github.com/NyaMisty/AltServer-Linux/releases/tag/v0.0.3-rc1

**Comment by NyaMisty** [comment]
I don't have iOS 15 devices. I'll close this issue for now, feel free to comment and let me reopen if there's problem.

**Comment by powenn** [comment]
> I don't have iOS 15 devices. I'll close this issue for now, feel free to comment and let me reopen if there's problem.

iOS 15works,but device number error still exists,I can only install Altstore one time ,Installation after that always have device number error, but daemon works fine.

**Comment by ramondunker** [comment]
For some reason I keep getting this same error:
```A device with number 'UDID' already exists on this team. (35)```

I logged out from my iCloud and did a full reinstall of Altserver but can't find a fix.
Does anyone know of a solution?

**Comment by Guztaver** [comment]
Any updates? I still getting this in iOS 15 :\

**Comment by TimestaticYT** [comment]
If you're on iOS 15 I recommend trying Trollstore so you won't have to resign. Try using another Apple acount or reinstall altstore. I don't know how I fixed it but after I while i don't seam to have the problem anymore. Also I was using the unofficial version Altstore linux at that time which might have caused issues
