### ISSUE TITLE
Cannot build AltServerNet for all platforms!

### ISSUE THREAD

**Issue by BlueDruddigon** [NyaMisty/AltServer-Linux#35]
Within the source code that author has provided, I have followed all steps in README for building AltServer!
I've tried to build AltServer and AltServerUPnP and it works fine.
But when trying to build AltServerNet, it always failed.
I read the Make file and found that the CFLAGS variable hadn't been used.
Please fix that.
By the way, the AltServer install ipa but the app installed immediately crash!
The version of AltStore: 1.4.8
iOS version: 14.8.1
iPhone 12 Pro!

**Comment by Macleykun** [comment]
I sadly can't get it to build with the steps provided. You happen to have some more clearer steps?

Then i can make a script to do these steps for me, to make it easier to build this in the future :-) (or improve readme heh)

**Comment by BlueDruddigon** [comment]
> I sadly can't get it to build with the steps provided. You happen to have some more clearer steps?
> 
> Then i can make a script to do these steps for me, to make it easier to build this in the future :-) (or improve readme heh)

All I do is follow the README!
My steps:
```
1. docker run -it --platform=linux/arm/v7 --name altserver-builder-alpine-armv7 alpine
2. Go to google.com on browser, search for corecrypto and go to the link of apple, scroll down and click the download button in corecrypto module. Wait for browser download, then do the following: 
    unzip corecrypto.zip; cd corecrypto; mkdir build; cd build; CC=clang CXX=clang++ cmake ..;
After that, type vim CMakeFiles/Makefile2 to the terminal, delete 2 line with `corecrypto_perf/....` and `corecrypto_test/.....` (line 66, 67) then type `make; make install`
3. git clone --recursive https://github.com/microsoft/cpprestsdk; cd cpprestsdk; mkdir build; cmake -DBUILD_SHARED_LIBS=0 ..; make; make install
4. git clone https://github.com/nih-at/libzip; cd libzip; mkdir build; cd build; cmake -DBUILD_SHARED_LIBS=0 ..; make; make install
5. git clone --recursive https://github.com/NyaMisty/AltServer-Linux; make NO_USBMUXD_STUB=1 NO_UPNP_STUB=1
```

Follow these steps and you will build AltServer for Linux x86_64 successfully.
