### ISSUE TITLE
Exception: Error in SSL handshake

### ISSUE THREAD

**Issue by mrngomez** [NyaMisty/AltServer-Linux#37]
Hello everyone,

First of all, thanks a lot for this project. I've been trying to jailbreak a really old iPad 2 2011, without success for the moment.

My setup is the following:
  - Using the latest tag: https://github.com/NyaMisty/AltServer-Linux/releases/tag/v0.0.2-1
  - (I've found myself unable to compile from source this project, seems like apple's corecrypto library is missing its cmakefile)
  - Downloaded  AltServer_aarch64 and copied it to a running arm64v8/ubuntu docker container with QEMU installed.
  - Successfuly started AltServer inside the container, but, the following error appears when trying to install Phoenix6 IPA:
  
  
![image](https://user-images.githubusercontent.com/25464952/156905471-aabeadec-95be-43ab-ad96-a2ca7b2465d9.png)

I've been unable to get any more logs out of it.

Best regards.

**Comment by paypay-a** [comment]
What are you trying to install to if your trying to jailbreak iOS 9.3.5. I have the same error though. P.s. ios 9.3.5 isn’t supported by altstore/altserver

**Comment by ghost** [comment]
im still getting this error while installing IB2X, why was this closed wth no comment? :/
