### ISSUE TITLE
Issue with packaging and releases

### ISSUE THREAD

**Issue by dada513** [NyaMisty/AltServer-Linux#39]
So, after failing to make a source package because of #29, I decided to try altserver-bin
Unfortunetly, it doesn't work anymore so I tried to update it.
There are a couple of upstream issues though:
- 0.0.2 was removed, and 0.0.2-1 was made, which (accidentally?) removed the x86 build
- 0.0.2-1 is hard to use in packages. the pkgrel (after the dash) is supposed to be used for packages to signal something being updated in the package but not upstream, and it gets messy when upstream has versions with a `-1` for example

**Comment by NyaMisty** [comment]
Sorry as I thought it's a simple SINGLE file app. I can't really know why you guys want to make it an AUR package.
But anyway I re-published the x86 build in latest prerelease (i586). Hope helpful
