### ISSUE TITLE
Fedora support

### ISSUE THREAD

**Issue by master-of-darkness** [NyaMisty/AltServer-Linux#43]
Hi! I`m using Fedora and I can`t run this app. Can you please do Fedora rpm support?

**Comment by Bradovman** [comment]
it seems, to work on my Fedora machine. What Fedora version are you running? Did you make sure your using the correct binary for your computers architecture?

**Comment by NyaMisty** [comment]
AltServer is a static binary file, should be able to run in any platform from Ubuntu to Arch to Alpine.

**Comment by master-of-darkness** [comment]
I'm getting error while using alien to convert from .deb to .rpm fedora-like
It just not starting, I will try to make screen of this
