### ISSUE TITLE
AltServer Over Network

### ISSUE THREAD

**Issue by BlueDruddigon** [NyaMisty/AltServer-Linux#45]
Can you please publish the AltServerNet binary for amd64?
I've followed through with all steps but didn't build the AltServerNet with success!

**Comment by NyaMisty** [comment]
Please use usbfluxd (pls Google for corellium/usbfluxd) instead, as that is much more reliable.

**Comment by BlueDruddigon** [comment]
> Please use usbfluxd (pls Google for corellium/usbfluxd) instead, as that is much more reliable.

Thank you for your response. I will try!
