### ISSUE TITLE
[Suggestion] Openwrt Support

### ISSUE THREAD

**Issue by friendlypandabytes** [NyaMisty/AltServer-Linux#5]
Since openwrt is linux-based, it would be nice to have a version of altserver running on openwrt, so refresh could occur automatically over the network.

**Comment by turannul** [comment]
Altserver in router that’s awesome idea. I wish this possible

**Comment by NyaMisty** [comment]
Currently totally not working over network (due to lacking of avahi)

**Comment by friendlypandabytes** [comment]
@NyaMisty, I believe avahi can be implemented in openwrt with the help of the pip3.

**Comment by turannul** [comment]
> Currently totally not working over network (due to lacking of avahi)



> @NyaMisty, I believe avahi can be implemented in openwrt with the help of the pip3, since python packages can be installed on openwrt. (I'm not sure, but I think that avahi is even available as a opkg package)

Hi this thing may help to work over network  https://github.com/corellium/usbfluxd

**Comment by NyaMisty** [comment]
Should be, but needs someone to develop it.
