### ISSUE TITLE
AltServer could not find this device.

### ISSUE THREAD

**Issue by kerim-dev** [NyaMisty/AltServer-Linux#50]
When i want to refresh in AltStore, then promt "AltServer could not find this device. / make sure  you have trusted this device with your computer and wifi sync is enabled. "

in console i see this:

Represented Value: 596
Sent Bytes Count: 4 (4)
Sent Data: 4 Bytes
Sent Bytes Count: 596 (596)
Sent Data: 596 Bytes
Finished handling request!
Other Socket:7. Port: 54649. Error: 0
Receiving request size...
Checking socket: 7
Received bytes: 4(of 4)
Receiving 33747 bytes...
Checking socket: 7
Received bytes: 1448(of 33747)
Checking socket: 7
Received bytes: 5544(of 33747)
Checking socket: 7
Received bytes: 9640(of 33747)
Checking socket: 7
Received bytes: 10136(of 33747)
Checking socket: 7
Received bytes: 11584(of 33747)
Checking socket: 7
Received bytes: 15680(of 33747)
Checking socket: 7
Received bytes: 19776(of 33747)
Checking socket: 7
Received bytes: 23872(of 33747)
Checking socket: 7
Received bytes: 27968(of 33747)
Checking socket: 7
Received bytes: 31856(of 33747)
Checking socket: 7
Received bytes: 33304(of 33747)
Checking socket: 7
Received bytes: 33747(of 33747)
Represented Value: 86
Sent Bytes Count: 4 (Failed to4)
Sent Data: 4 Bytes
 handle request:AltServeSent Bytes Count: 86 (86)
Sent Data: 86 Bytes
r could not find the device.

**Comment by NyaMisty** [comment]
do `idevice_id -l -n` and see if your device are in it.
If not, you have to plugin your device to pair it

**Comment by NyaMisty** [comment]
dup #49
