### ISSUE TITLE
Refusal to operate after removing device access from iCloud.

### ISSUE THREAD

**Issue by tduxp** [NyaMisty/AltServer-Linux#52]
Hey, AltServer-Linux works great. Although, there seems to be a problem for me. During some troubleshooting steps, I accidentally removed the 'iMac' created by this program within the authorized devices located in Settings. So, whenever I try to refresh or install any applications, it returns multiple errors: 

Received auth response status code: 200
Received auth response status code: 200
Alert: Could not install YouTube-Custom.ipa to unknown.
Unable to sign you in to your Apple ID. Try again later. (-36607)

I suppose the device is blacklisted from my Apple ID, is there anyway to spoof the device created so this program will operate normally again? (The password is definitely correct)

Thanks in advance.

**Comment by tduxp** [comment]
After some more troubleshooting, I tried setting up alt_anisette_server on a spare VPS laying around, except the fact that it refuses to launch...so, I guess, I'm stuck using my Windows VM to refresh AltStore then. Unless somehow I can do some packets capturing while refreshing AltStore on my MacBook or Windows, but I guess unencrypted communication is pretty rare...

Or
Does anyone have an alternative to https://armconverter.com/anisette/irGb3Quww8zrhgqnzmrx? because that one appears to be blacklisted/broken for me.

Thanks again.

**Comment by tduxp** [comment]
After some more troubleshooting, I tried setting up alt_anisette_server on a spare VPS laying around, except the fact that it refuses to launch...so, I guess, I'm stuck using my Windows VM to refresh AltStore then. Unless somehow I can do some packets capturing while refreshing AltStore on my MacBook or Windows, but I guess unencrypted communication is pretty rare...

Or
Do you have an alternative to

**Comment by tduxp** [comment]
After running docker container, the result is: ![this](https://user-images.githubusercontent.com/94144761/164846854-ce869a57-40bd-4e98-89f3-3788e6ea99b8.png).

**Comment by tduxp** [comment]
Another update, I managed to retrieved the anisette data from my MacBook, and instead of showing the 'Unable to sign you in to your Apple ID. Try again later. (-36607)', the login page spins forever until it says, 'Failed to login, request canceled by user'. I thought this was a my-issue thing, but apparently Apple made a change. I was using this programs for months with issue, but RIP. I unless the docker-container works, I'm considering switching back to my old way lol.

**Comment by NyaMisty** [comment]
macOS anisette server aren't supported by me, so sadly can't help you.
Wine anisette server should work fine tho.

**Comment by NyaMisty** [comment]
If still fails please submit a new  issue in the alt-anisette-server repo
