### ISSUE TITLE
Docker Image of AltServer

### ISSUE THREAD

**Issue by Centterm** [NyaMisty/AltServer-Linux#54]
Hello,

I usually manage all my homelab services with docker. It would be awesome to manage AltServer like all my other services in docker as well. That would be much cleaner solution than running everything in tmux/screen or as systemd services. So what would it take to get a docker image with a proper example compose file and manual - is it even feasible at all?

There are some hurdles but none is a real showstopper:
- Have a way to not only run AltServer permanently as a daemon but also add ipa. Could be solved with `docker run -rm -it` or `docker exec` on an existing container. Maybe even docker secrets could help.
- Custom Anisette Server could directly be integrated in the example compose file
- usb access could be granted with the docker `device` key
- To my understanding wifi refresh depends on multicast traffic. Thus it would not be enough to simply expose a port like one usually does with a docker service. The network mode host could be used or even a bit cleaner to not collider with other services a macvlan interface could be integrated in the example compose file. The intial setup with netmuxd could be a bit more complicated but all dependencies could be packaged in the docker image and maybe an additional script could simplify the whole initial pairing process? 

What are your thoughts?

**Comment by NyaMisty** [comment]
Needn't and not possible

**Comment by Centterm** [comment]
Could you please be so kind and elaborate your statement a bit more? 

"Needn't" might be a relative term. Personally, I would "need" something like this. The "let it live in screen" approach is not really feasible on a server. Imagine every server-service would require something like this. I get that for you development this would not help, but for the actual user using the software in "production"?

Why is it not possible? What besides the above mentioned hurdles prevent dockerizing AltServer?

**Comment by NyaMisty** [comment]
No, because I don't have time.

It's a SINGLE FILE program without any dependencies, so docker is not needed at all
Docker is not possible because mDNS relies on avahi, and avahi does not work with docker.

**Comment by Centterm** [comment]
> No, because I don't have time. 

Who said you should do it? It would have been a pleasure to try this, report back to you and support this project with submitting a PR in case you would have welcomed it. 

>  It's a SINGLE FILE program without any dependencies, so docker is not needed at all

It depends on avahi, netmuxd and a custom anisette server. Dependency management is not the only use case for docker. Maybe I don't want to give access to all my files? Maybe it would be much easier to simply run `docker-compose up` than writing custom systemd services or leaving it running in screen/tmux on a headless server? Many other home-lab applications live in docker and thus managed from one point. 


> mDNS relies on avahi, and avahi does not work with docker.

I don't think this quite correct. Broadcast traffic can be made available to docker containers with either the host mode, a macvlan or reflecting the broadcast (something like mdns-reflector). 

Anyway, while I disagree with your general "Needn't and not possible", I totally get that this is your project and you are simply not interested.

**Comment by OscarVanL** [comment]
A docker image would be invaluable to me so I could run the server on my Synology NAS.

**Comment by DrissiReda** [comment]
I would also be interested in a Docker image.

**Comment by aquelemiguel** [comment]
Why is this closed? A Docker image for RPi would be fantastic.
