### ISSUE TITLE
Unable to sign in to your Apple ID

### ISSUE THREAD

**Issue by Jannomag** [NyaMisty/AltServer-Linux#55]
Hi,
I just tried AltServer on my Ubuntu 20.04 server (amd64) and stuck on login.
It's just give me this:
```

Received auth response status code: 200
Received auth response status code: 200
Alert: Could not install 1_5.ipa to unknown.
    Unable to sign you in to your Apple ID. Try again later. (-36607)
Press any key to continue...

Error: com.rileytestut.AltServer.Localized (-36607).
Finished!

```

My command is `altserver -u UUID -a MY@APPLE.ID -p MYPASS /path/to/ipa`

I tried it with cable and also wirelessly, both usbmuxd and netmuxd works by showing me the device id using `idevice_id -l`.

Apple ID and password are correct, I tried to login on iCloud.com by copy-paste the data.

I also run the alt-anisette-server docker and get a response with `curl 127.0.0.1:6969` and set the environment variable by executing `env ALTSERVER_ANISETTE_SERVER=127.0.0.1:6969`

Any ideas how to fix it?

**Comment by NyaMisty** [comment]
See #40

**Comment by Jannomag** [comment]
Shouldn't the mentioned docker container alt-anisette-server work then?

**Comment by NyaMisty** [comment]
Oh sorry I missed that part in email!

**Comment by NyaMisty** [comment]
Can you help to confirm that when using alt-anisette-server, the anisette response have things like `Windows` init?

(I mean when signing apps, in the console output of AltServer-Linux)

**Comment by Jannomag** [comment]
I don't know where to find this, I hope this helps:

Output of `curl 127.0.0.1:6969`:
```
{"X-Apple-I-Client-Time":"2022-05-08T18:29:35Z","X-Apple-I-MD":"AAAABQAAABDo40a5H7R93nl1lsybf3zGAAAAAg==","X-Apple-I-MD-LU":"NUUwMzczOEItMDNGNi00NkI1LTlBNkEtRjAyMjI3OUIzMDQw","X-Apple-I-MD-M":"xjcezsA33TCMtJWym+NkY2bQVof4X4p8l5OMSyuwswE3zIHMlribko0DvYHwgZqlbRtxYFtFzYnvu+yB","X-Apple-I-MD-RINFO":"17106176","X-Apple-I-SRL-NO":"C02LKHBBFD57","X-Apple-I-TimeZone":"PST","X-Apple-Locale":"en_US","X-MMe-Client-Info":"<MacBookPro15,1> <Mac OS X;10.15.2;19C57> <com.apple.AuthKit/1 (com.apple.dt.Xcode/3594.4.19)>","X-Mme-Device-Id":"5E03738B-03F6-46B5-9A6A-F022279B3040"}
```

Output of altserver command:
```
Installing app...
Received response status code: 200
parse anisette data ret
Got anisetteData json: {"X-Apple-I-Client-Time":"2022-05-08T18:31:59Z","X-Apple-I-MD":"AAAABQAAABCOmBgXFi5kzWZ3XVeFLVynAAAAAQ==","X-Apple-I-MD-LU":"CE99147F8610526892ED1AC53931EF38552A2CB64C2DC433D242FDAE789A7F80","X-Apple-I-MD-M":"wbxShQ1m2WmGT+Sf496k3tYfwQhrzQ+79dQKNUVBzpz/rO+4faO/k3ZjePXDCXk1jMefsXn7NllulZOH","X-Apple-I-MD-RINFO":"17106176","X-Apple-I-SRL-NO":"0","X-Apple-I-TimeZone":"GMT+0","X-Apple-Locale":"en_GB","X-MMe-Client-Info":"<iMac11,3> <Mac OS X;10.15.6;19G2021> <com.apple.AuthKit/1 (com.apple.dt.Xcode/3594.4.19)>","X-Mme-Device-Id":"F6C158F4-BD50-4EDD-B897-9BE4349EEED5"}
X-Apple-I-MD-M: wbxShQ1m2WmGT+Sf496k3tYfwQhrzQ+79dQKNUVBzpz/rO+4faO/k3ZjePXDCXk1jMefsXn7NllulZOH
X-Apple-I-MD: AAAABQAAABCOmBgXFi5kzWZ3XVeFLVynAAAAAQ==
X-Apple-I-MD-LU: CE99147F8610526892ED1AC53931EF38552A2CB64C2DC433D242FDAE789A7F80
X-Apple-I-MD-RINFO: 17106176
X-Mme-Device-Id: F6C158F4-BD50-4EDD-B897-9BE4349EEED5
X-Apple-I-SRL-NO: 0
X-MMe-Client-Info: <iMac11,3> <Mac OS X;10.15.6;19G2021> <com.apple.AuthKit/1 (com.apple.dt.Xcode/3594.4.19)>
X-Apple-I-Client-Time: 2022-05-08T18:31:59Z
X-Apple-Locale: en_GB
X-Apple-I-TimeZone: GMT+0
Building anisetteData obj...
MachineID : CENSORED
One-Time Password: CENSORED
Local User ID: CENSORED
Device UDID: CENSORED
Device Description: <iMac11,3> <Mac OS X;10.15.6;19G2021> <com.apple.AuthKit/1 (com.apple.dt.Xcode/3594.4.19)>
Date: 2022-05-08T17:31:59Z
Received auth response status code: 200
Received auth response status code: 200
Alert: Could not install 1_5.ipa to unknown.
    Unable to sign you in to your Apple ID. Try again later. (-36607)
Press any key to continue...

Error: com.rileytestut.AltServer.Localized (-36607).
Finished!
```

**Comment by NyaMisty** [comment]
yup, exactly.
You are not using alt-anisette-server

**Comment by Jannomag** [comment]
Okay? I've set the env as I mentioned in my first post.
Was this wrong? 

Edit: it was. Using `export ALTSERVER_ANISETTE_SERVER=http://127.0.0.1:6969` works (maybe add this to the readme to make this clear?)

But now I got this error:

```
Alert: Could not install 1_5.ipa to unknown.
    AltServer could not find the device. Make sure you have trusted this device with your computer and WiFi sync is enabled.
```

I already connected the iPhone via usb and trusted the Linux server on my iPhone. Now I'm using netmuxd.
Do I need to install ipa using cable and just can resign them?

**Comment by NyaMisty** [comment]
I believe so, pairing problem is really out of this repo's scope. 
Make sure ideviceinstaller command is working with your setup

**Comment by Jannomag** [comment]
Just for posterity:
It's working now. I killed netmuxd, started usbmuxd, connected my iPhone (12, iOS 15.1.1) via lightning cable and installed the latest AltStore using the above given AltServer command. Then I killed usbmuxd, started netmuxd, disconnected my iPhone and was able to install an IPA directly on my iPhone and even resign was working.
