### ISSUE TITLE
can AltServer-Linux work with this non-standard network configuration?

### ISSUE THREAD

**Issue by machineonamission** [NyaMisty/AltServer-Linux#61]
![image](https://user-images.githubusercontent.com/35177464/170328283-a93e4e28-2c69-4502-9c4b-c882f2168daf.png)
in this configuration, my ipad can't access altserver
I can access the computer just fine via ssh and other services over wifi so that's not the issue
when i directly connect my ipad to the modem, it can communicate just fine
is it possible to setup altserver/store to work in this config?

**Comment by jkcoxson** [comment]
This is a limitation with the AltStore app that a few of us a actively solving. It’ll be a bit until it’s done.

**Comment by machineonamission** [comment]
wasn't aware it was already in progress, neat.
are there any current workarounds? (without modifying the network configuration)

**Comment by jkcoxson** [comment]
There are no workarounds besides sideloading through AltServer instead of through the app.

**Comment by machineonamission** [comment]
got it. are there any open issues on other repos I should follow for info about when this is implemented?

**Comment by NyaMisty** [comment]
AltStore guys doesn't even care about us, so you'd better use some alternative method.
1. Method1: You can setup an iptables to NAT your AltServer's 192.168.1.66 to something like 10.0.0.2
2. Method2: You can simply plug-in two network cable to your AltServer lol

**Comment by machineonamission** [comment]
> 1. Method1: You can setup an iptables to NAT your AltServer's 192.168.1.66 to something like 10.0.0.2

so as long as it's on the same IP range, altstore will be able to find it?

**Comment by jkcoxson** [comment]
I don't think that'll work, because it still relies on mDNS traversal. And from what the error looks like, it's failing to receive mDNS packets.

**Comment by NyaMisty** [comment]
> I don't think that'll work, because it still relies on mDNS traversal. And from what the error looks like, it's failing to receive mDNS packets.

Same IP range usually they are under same IP broadcast subnet, so mDNS would work

**Comment by machineonamission** [comment]
> Method1: You can setup an iptables to NAT your AltServer's 192.168.1.66 to something like 10.0.0.2

Is there a guide/info anywhere on how to do this? I'm having trouble figuring it out
