### ISSUE TITLE
This device is already associated with other accounts in the Apple Developer Program or the Apple Developer Enterprise Program. Please use a different device. (-38607)

### ISSUE THREAD

**Issue by githubashutoshsoni** [NyaMisty/AltServer-Linux#65]
I keep getting the error. It was working fine for a few months but now suddenly stopped working..

**Comment by githubashutoshsoni** [comment]
i just removed the ipa from the iPhone and installed.seems to be fixed.

**Comment by PandaPootchy** [comment]
Did u install using this version or the windows version?

**Comment by githubashutoshsoni** [comment]
No. linux version.

**Comment by PandaPootchy** [comment]
Interesting because im having this same issue but because of a different problem at #86
