### ISSUE TITLE
100% CPU Usage on App-install

### ISSUE THREAD

**Issue by zimsneexh** [NyaMisty/AltServer-Linux#66]
As the title says, basically. Installing an .ipa from AltStore causes the AltServer host CPU to jump to 100% and it doesn't seem to drop even after 10-15 minutes of waiting. Refreshing does not have this issue.

**Comment by federicotorrielli** [comment]
Installing an .ipa means signing that .ipa. Having a thread at 100% it's not a problem at all, it's standard.
