### ISSUE TITLE
AltServer ignores IPA, always runs as daemon (SOLUTION)

### ISSUE THREAD

**Issue by jmans25** [NyaMisty/AltServer-Linux#9]
Altserver Build Configuration 1 appears to be ignoring the option to Install an IPA, instead it always runs in daemon mode, even if an IPA file, UDID, username, and password are specified. 

**_SOLUTION:_**
**src/AltServerMain.cpp -> Line 166**, add `installApp = true;` https://github.com/NyaMisty/AltServer-Linux/blob/583230792be18c9f77710ee80496153187dffadb/src/AltServerMain.cpp#L166

Change
```
    } else if (optind + 1 == argc) {
		ipaPath = argv[optind];
```

To
```
    } else if (optind + 1 == argc) {
		ipaPath = argv[optind];
		installApp = true;
```

Hope that helps!

**Comment by 0x8ff** [comment]
Ty
