### ISSUE TITLE
There is no provisioning profile with the requested identifier on this team

### ISSUE THREAD

**Issue by OSS-GR** [NyaMisty/AltServer-Linux#95]
Are there any plans to update the project so it works with the what is still in beta solution for this new altserver that fixes this error?

**Comment by EnderMaster77** [comment]
This issue has been fixed in the newer version of altstore and presumably the windows version of altserver. However, I believe that this port of altserver is installing an outdated version of altstore that has this bug.

**Comment by boat1337** [comment]
The solution is in altstore, not altserver, does not need to be updated

**Comment by OSS-GR** [comment]
Does that mean you have it working now?
> The solution is in altstore, not altserver, does not need to be updated

**Comment by boat1337** [comment]
> Does that mean you have it working now?
> 
> > The solution is in altstore, not altserver, does not need to be updated

yes, it's working, I only had to update AltStore

**Comment by OSS-GR** [comment]
> > Does that mean you have it working now?
> > > The solution is in altstore, not altserver, does not need to be updated
> 
> yes, it's working, I only had to update AltStore

Thanks that worked man.

**Comment by Rubiooo04** [comment]
When I update the altstore, it won't let me get that error and if I reinstall it, that error keeps coming out. Any solution?

**Comment by boat1337** [comment]
> When I update the altstore, it won't let me get that error and if I reinstall it, that error keeps coming out. Any solution?

Weird, I updated altstore through altserver-linux command line and it works fine

**Comment by Rubiooo04** [comment]
> 

What version do you have when you reinstall it?

**Comment by boat1337** [comment]
1.6.2

**Comment by Rubiooo04** [comment]
> 1.6.2

I still have 1.5.1 even though I reinstall it

![IMG_7811](https://user-images.githubusercontent.com/77902247/227716676-f4c7eeeb-1a1d-4d76-a613-5726d34b1664.jpg)

**Comment by boat1337** [comment]
> > 1.6.2
> 
> I still have 1.5.1 even though I reinstall it
> 
> ![IMG_7811](https://user-images.githubusercontent.com/77902247/227716676-f4c7eeeb-1a1d-4d76-a613-5726d34b1664.jpg)

please download latest altstore from here and try again: https://cdn.altstore.io/file/altstore/apps/altstore/1_6_2.ipa

**Comment by Rubiooo04** [comment]
> > > 1.6.2
> > 
> > 
> > I still have 1.5.1 even though I reinstall it
> > ![IMG_7811](https://user-images.githubusercontent.com/77902247/227716676-f4c7eeeb-1a1d-4d76-a613-5726d34b1664.jpg)
> 
> please download latest altstore from here and try again: https://cdn.altstore.io/file/altstore/apps/altstore/1_6_2.ipa

Thank you very much, I managed to solve it with that ipa <3
