### ISSUE TITLE
[SOLVED] There is no provisioning profile with the requested identifier on this team

### ISSUE THREAD

**Issue by Rubiooo04** [NyaMisty/AltServer-Linux#97]
Hi there

I know there is a closed ticket, but the solution for that ticker doesn't work for me

When I try to update the altstore from the iphone I get the error.
In the description of the update it says that it is installed when the altstore is reinstalled from the altserver but even though I reinstall it from the altserver the same thing still happens to me

Could it be that this altserver is outdated?

**Comment by fucksophie** [comment]
What? Why'd you close this issue? Did you fix it?

**Comment by Rubiooo04** [comment]
> reglaste?

That's what the solution was about, it was very easy, I just had to give the i option (install altserver) and then the 2 option (install through an ipa) and I downloaded the ipa from this page https://cdn.altstore.io/file/altstore/apps/altstore/1_6_2.ipa and put it in the folder ipa ( which is in the same directory as run.sh )
